image: node:20.15.0-alpine
stages:
  - build
cache:
  paths:
    - node_modules/
install_dependencies:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
