#!/bin/sh
set -e

echo "Starting API DB script..."
echo "Creating user $KEYCLOAK_DB_USER for $KEYCLOAK_DB_DATABASE and password $POSTGRES_PASSWORD"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$KEYCLOAK_DB_DATABASE" <<-EOSQL
  BEGIN;

  CREATE USER $KEYCLOAK_DB_USER WITH SUPERUSER PASSWORD '$KEYCLOAK_DB_PASSWORD';

  GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB_DATABASE TO $KEYCLOAK_DB_USER;

  COMMIT;
EOSQL
