#!/bin/sh
set -e

echo "Starting API DB script..."
echo "Creating user $TYPEORM_USERNAME for $TYPEORM_DATABASE"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$TYPEORM_DATABASE" <<-EOSQL
  BEGIN;

  CREATE USER $TYPEORM_USERNAME WITH SUPERUSER PASSWORD '$TYPEORM_PASSWORD';

  GRANT ALL PRIVILEGES ON DATABASE $TYPEORM_DATABASE TO $TYPEORM_USERNAME;

  COMMIT;
EOSQL
